-- CRIAR BANCO DE DADOS
CREATE DATABASE TesteSegurancaSA3

-- COLOCAR O BANCO EM USO
USE TesteSegurancaSA3

-- REALIZAR CRIAÇÃO DE TABELA NO BANCO DE DADOS
CREATE TABLE Usuarios
(
Id INT PRIMARY KEY IDENTITY,
Email VARCHAR(100) UNIQUE NOT NULL,
Senha VARCHAR(50) NOT NULL
);

-- INSERIR DADOS NO BANCO E DADOS

INSERT INTO Usuarios VALUES ('email@email.com', 1234);

-- CONSULTAR OS USUARIOS EXISTNTES
SELECT * FROM Usuarios

-- HASHEANDO CAMPOS DO BANCO DE DADOS
SELECT Email, Senha FROM Usuarios;

SELECT Email, HASHBYTES('MD2', Senha) FROM Usuarios;

SELECT Id, Email, HASHBYTES('MD2', Senha) AS 'SENHA HASH' FROM Usuarios WHERE Id = 1;
SELECT Id, Email, HASHBYTES('MD4', Senha) AS 'SENHA HASH' FROM Usuarios WHERE Id = 1;
SELECT Id, Email, HASHBYTES('MD5', Senha) AS 'SENHA HASH' FROM Usuarios WHERE Id = 1;
SELECT Id, Email, HASHBYTES('SHA', Senha) AS 'SENHA HASH' FROM Usuarios WHERE Id = 1;
SELECT Id, Email, HASHBYTES('SHA1', Senha) AS 'SENHA HASH' FROM Usuarios WHERE Id = 1;
SELECT Id, Email, HASHBYTES('SHA2_256', Senha) AS 'SENHA HASH' FROM Usuarios WHERE Id = 1;
SELECT Id, Email, HASHBYTES('SHA2_512', Senha) AS 'SENHA HASH' FROM Usuarios WHERE Id = 1;